### ISSUE TITLE
释放内存咨询

### ISSUE THREAD

**Issue by zmmzhaomaomao** [yline/as_x_modlestudy#1]
博主您好：
        感谢您的代码开源。

在查阅native-manager.cpp的代码中，发现一个地方未释放内存，由于我对JNI知识和C/C++知识的了解有限，不知是否合理。故此，向您发出咨询。
疑惑代码如下：
`jstring Java_com_ndk_jni_JniManager_encode(JNIEnv *env, jobject, jstring msg, jint type) {
    PrintStart();

    // 字符长度
    size_t length = (size_t) env->GetStringUTFLength(msg);

    // 字符内容
    unsigned char *c_msg = NULL;
    c_msg = (unsigned char *) env->GetStringUTFChars(msg, 0);

    // 加密后的数组
    char *result = NULL;
    result = b64_encode(c_msg, length);

    // 加密后的字符串
    return env->NewStringUTF(result);
}`
是否需要对c_msg进行释放？  调用env->ReleaseStringUTFChars方法？

**Comment by yline** [comment]
> 博主您好：
> 感谢您的代码开源。
> 
> 在查阅native-manager.cpp的代码中，发现一个地方未释放内存，由于我对JNI知识和C/C++知识的了解有限，不知是否合理。故此，向您发出咨询。
> 疑惑代码如下：
> `jstring Java_com_ndk_jni_JniManager_encode(JNIEnv *env, jobject, jstring msg, jint type) {
> PrintStart();
> 
> ```
> // 字符长度
> size_t length = (size_t) env->GetStringUTFLength(msg);
> 
> // 字符内容
> unsigned char *c_msg = NULL;
> c_msg = (unsigned char *) env->GetStringUTFChars(msg, 0);
> 
> // 加密后的数组
> char *result = NULL;
> result = b64_encode(c_msg, length);
> 
> // 加密后的字符串
> return env->NewStringUTF(result);
> ```
> 
> }`
> 是否需要对c_msg进行释放？ 调用env->ReleaseStringUTFChars方法？

谢谢你的建议，你自己实现可以添加。
我当初写的时候只是作为一个jni实现的demo。

**Comment by zmmzhaomaomao** [comment]
> > 博主您好：
> > 感谢您的代码开源。
> > 在查阅native-manager.cpp的代码中，发现一个地方未释放内存，由于我对JNI知识和C/C++知识的了解有限，不知是否合理。故此，向您发出咨询。
> > 疑惑代码如下：
> > `jstring Java_com_ndk_jni_JniManager_encode(JNIEnv *env, jobject, jstring msg, jint type) {
> > PrintStart();
> > ```
> > // 字符长度
> > size_t length = (size_t) env->GetStringUTFLength(msg);
> > 
> > // 字符内容
> > unsigned char *c_msg = NULL;
> > c_msg = (unsigned char *) env->GetStringUTFChars(msg, 0);
> > 
> > // 加密后的数组
> > char *result = NULL;
> > result = b64_encode(c_msg, length);
> > 
> > // 加密后的字符串
> > return env->NewStringUTF(result);
> > ```
> > 
> > 
> > }`
> > 是否需要对c_msg进行释放？ 调用env->ReleaseStringUTFChars方法？
> 
> 谢谢你的建议，你自己实现可以添加。
> 我当初写的时候只是作为一个jni实现的demo。

感谢回复～
之前由于对JNI知识了解的不足，所以提出了该问题。近期已加强了对JNI基础知识的了解～
